# Generated by Django 3.2 on 2025-06-12 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('store_meta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_user_addresses', to='store_meta.store'),
        ),
    ]
