# Generated by Django 3.2 on 2025-06-12 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0002_useraddress_store'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store_meta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_address_shipping', to='address.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_meta.store'),
        ),
        migrations.AlterUniqueTogether(
            name='useraddress',
            unique_together={('user', 'hash')},
        ),
    ]
