# Generated by Django 3.2 on 2025-05-16 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0001_initial'),
        ('basket', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='stockrecord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_lines', to='partner.stockrecord', verbose_name='Stock record'),
        ),
    ]
