# Generated by Django 3.2 on 2025-05-16 21:38

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offer', '0001_initial'),
        ('store_meta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='This will be shown in the checkout and basket once the voucher is entered', max_length=128, verbose_name='Name')),
                ('code', models.CharField(db_index=True, help_text='Case insensitive / No spaces allowed', max_length=128, unique=True, verbose_name='Code')),
                ('usage', models.CharField(choices=[('Single use', 'Can be used once by one customer'), ('Multi-use', 'Can be used multiple times by multiple customers'), ('Once per customer', 'Can only be used once per customer')], default='Multi-use', max_length=128, verbose_name='Usage')),
                ('start_datetime', models.DateTimeField(db_index=True, verbose_name='Start datetime')),
                ('end_datetime', models.DateTimeField(db_index=True, verbose_name='End datetime')),
                ('num_basket_additions', models.PositiveIntegerField(default=0, verbose_name='Times added to basket')),
                ('num_orders', models.PositiveIntegerField(default=0, verbose_name='Times on orders')),
                ('total_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total discount')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Voucher',
                'verbose_name_plural': 'Vouchers',
                'ordering': ['-date_created'],
                'get_latest_by': 'date_created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VoucherOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_voucher_offers', to='offer.conditionaloffer')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_voucher_offers', to='voucher.voucher')),
            ],
            options={
                'unique_together': {('voucher', 'offer')},
            },
        ),
        migrations.CreateModel(
            name='VoucherGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_linked_groups', to='voucher.voucher')),
                ('main_voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_main_groups', to='voucher.voucher')),
            ],
            options={
                'unique_together': {('main_voucher', 'linked_voucher')},
            },
        ),
        migrations.CreateModel(
            name='VoucherApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_voucher_apps', to='order.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_voucher_apps', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_applications', to='voucher.voucher')),
            ],
        ),
        migrations.AddField(
            model_name='voucher',
            name='applications',
            field=models.ManyToManyField(related_name='store_voucher_set', through='voucher.VoucherApplication', to='order.Order', verbose_name='Applications'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='offers',
            field=models.ManyToManyField(related_name='store_vouchers', through='voucher.VoucherOffer', to='offer.ConditionalOffer'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_vouchers', to='store_meta.store', verbose_name='Store'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='voucher_set',
            field=models.ManyToManyField(blank=True, related_name='store_voucher_groups', through='voucher.VoucherGroup', to='voucher.Voucher'),
        ),
        migrations.CreateModel(
            name='VoucherSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('count', models.PositiveIntegerField(verbose_name='Number of vouchers')),
                ('code_length', models.IntegerField(default=12, verbose_name='Length of Code')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('start_datetime', models.DateTimeField(verbose_name='Start datetime')),
                ('end_datetime', models.DateTimeField(verbose_name='End datetime')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_voucher_sets', to='offer.conditionaloffer', verbose_name='Offer')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_voucher_sets', to='store_meta.store', verbose_name='Store')),
            ],
            options={
                'verbose_name': 'VoucherSet',
                'verbose_name_plural': 'VoucherSets',
                'ordering': ['-date_created'],
                'get_latest_by': 'date_created',
                'abstract': False,
                'unique_together': {('name', 'store')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='voucher',
            unique_together={('code', 'store')},
        ),
    ]
