# Generated by Django 3.2 on 2025-06-12 11:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchant', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=150, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_platform_admin', models.BooleanField(default=False)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=50, null=True)),
                ('provider_id', models.CharField(blank=True, max_length=100, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('language', models.CharField(default='en', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this customer belongs to.', related_name='_user_user_groups_+', related_query_name='+', to='auth.Group', verbose_name='groups')),
                ('primary_tenant', models.ForeignKey(blank=True, help_text="User's default tenant for quick access", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_users', to='merchant.merchant')),
                ('tenant_memberships', models.ManyToManyField(related_name='users', through='merchant.TenantMembership', to='merchant.Merchant')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this customer.', related_name='_user_user_user_permissions_+', related_query_name='+', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
