# Generated by Django 3.2 on 2025-06-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('merchant_admin', 'Merchant Admin'), ('store_manager', 'Store Manager'), ('store_staff', 'Store Staff'), ('accountant', 'Accountant'), ('customer_service', 'Customer Service'), ('store_customer', 'Store Customer'), ('public_admin', 'Platform Admin')], default='store_customer', max_length=32),
        ),
    ]
