# Generated by Django 3.2 on 2025-05-16 21:38

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('ssl_enabled', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('verification_method', models.CharField(blank=True, choices=[('dns', 'DNS Record'), ('file', 'File Upload'), ('meta', 'Meta Tag')], max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Store Domains',
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Official business/organization name', max_length=255, verbose_name='merchant name')),
                ('schema_name', models.CharField(default='merchant_schema', max_length=63, unique=True)),
                ('contact_email', models.EmailField(help_text='Primary contact email address', max_length=254, unique=True, verbose_name='contact email')),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Primary contact number with country code', max_length=128, null=True, region='US', verbose_name='contact phone')),
                ('timezone', models.CharField(default='UTC', help_text='Preferred timezone', max_length=50, verbose_name='timezone')),
                ('default_language', models.CharField(default='en', help_text='Preferred language code (ISO 639-1)', max_length=10, verbose_name='language')),
                ('domain_url', models.CharField(max_length=128, unique=True)),
                ('custom_domain', models.CharField(blank=True, help_text='Custom domain (store.com)', max_length=255, null=True)),
                ('status', models.CharField(choices=[('unverified', 'Unverified'), ('active', 'Active'), ('suspended', 'Suspended')], default='unverified', max_length=20, verbose_name='account status')),
                ('role', models.CharField(choices=[('public_admin', 'Public Admin'), ('merchant_admin', 'Merchant Admin'), ('store_manager', 'Store Manager'), ('store_customer', 'Store Customer')], default='merchant_admin', max_length=20)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_create_admin', models.BooleanField(default=True, help_text='Whether to automatically create admin user')),
            ],
            options={
                'verbose_name': 'Merchant',
                'verbose_name_plural': 'Merchants',
            },
        ),
    ]
