# Generated by Django 3.2 on 2025-06-12 11:05

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('ssl_enabled', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('verification_method', models.CharField(blank=True, choices=[('dns', 'DNS Record'), ('file', 'File Upload'), ('meta', 'Meta Tag')], max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Store Domains',
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Official business/organization name', max_length=255, verbose_name='merchant name')),
                ('schema_name', models.CharField(default='merchant_schema', max_length=63, unique=True)),
                ('contact_email', models.EmailField(help_text='Primary contact email address', max_length=254, unique=True, verbose_name='contact email')),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='US', verbose_name='contact phone')),
                ('timezone', models.CharField(default='UTC', max_length=50, verbose_name='timezone')),
                ('default_language', models.CharField(default='en', max_length=10, verbose_name='language')),
                ('domain_url', models.CharField(max_length=128, unique=True)),
                ('custom_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('unverified', 'Unverified'), ('active', 'Active'), ('suspended', 'Suspended')], default='unverified', max_length=20, verbose_name='account status')),
                ('role', models.CharField(choices=[('public_admin', 'Public Admin'), ('merchant_admin', 'Merchant Admin'), ('store_manager', 'Store Manager'), ('store_customer', 'Store Customer')], default='merchant_admin', max_length=20)),
                ('business_type', models.CharField(blank=True, choices=[('retail', 'Retail'), ('wholesale', 'Wholesale'), ('service', 'Service'), ('digital', 'Digital Products'), ('subscription', 'Subscription')], max_length=50)),
                ('plan_type', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('allow_user_registration', models.BooleanField(default=True)),
                ('require_invitation', models.BooleanField(default=False)),
                ('max_users', models.IntegerField(default=5)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_create_admin', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Merchant',
                'verbose_name_plural': 'Merchants',
            },
        ),
        migrations.CreateModel(
            name='TenantInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('merchant_admin', 'Merchant Admin'), ('store_manager', 'Store Manager'), ('store_staff', 'Store Staff'), ('accountant', 'Accountant'), ('customer_service', 'Customer Service')], max_length=20)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('merchant_admin', 'Merchant Admin'), ('store_manager', 'Store Manager'), ('store_staff', 'Store Staff'), ('accountant', 'Accountant'), ('customer_service', 'Customer Service')], max_length=20)),
                ('permission_level', models.CharField(choices=[('full', 'Full Access'), ('limited', 'Limited Access'), ('read_only', 'Read Only')], default='full', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_owner', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('invitation_token', models.CharField(blank=True, max_length=100, null=True)),
                ('invitation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('invitation_accepted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
    ]
