# Generated by Django 3.2 on 2025-05-16 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchant', '0001_initial'),
        ('store_meta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='stores',
            field=models.ManyToManyField(related_name='merchants', through='store_meta.StorePermission', to='store_meta.Store', verbose_name='Managed Stores'),
        ),
        migrations.AddField(
            model_name='domain',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='merchant.merchant'),
        ),
    ]
