# Generated by Django 3.2 on 2025-06-11 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store_meta', '0002_auto_20250520_0240'),
        ('merchant', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='allow_user_registration',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='business_type',
            field=models.CharField(blank=True, choices=[('retail', 'Retail'), ('wholesale', 'Wholesale'), ('service', 'Service'), ('digital', 'Digital Products'), ('subscription', 'Subscription')], max_length=50),
        ),
        migrations.AddField(
            model_name='merchant',
            name='max_users',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='merchant',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='merchant',
            name='require_invitation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='auto_create_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='US', verbose_name='contact phone'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='custom_domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='default_language',
            field=models.CharField(default='en', max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='stores',
            field=models.ManyToManyField(related_name='merchants', through='store_meta.StorePermission', to='store_meta.Store'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50, verbose_name='timezone'),
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('merchant_admin', 'Merchant Admin'), ('store_manager', 'Store Manager'), ('store_staff', 'Store Staff'), ('accountant', 'Accountant'), ('customer_service', 'Customer Service')], max_length=20)),
                ('permission_level', models.CharField(choices=[('full', 'Full Access'), ('limited', 'Limited Access'), ('read_only', 'Read Only')], default='full', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_owner', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('invitation_token', models.CharField(blank=True, max_length=100, null=True)),
                ('invitation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('invitation_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='merchant.merchant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('merchant_admin', 'Merchant Admin'), ('store_manager', 'Store Manager'), ('store_staff', 'Store Staff'), ('accountant', 'Accountant'), ('customer_service', 'Customer Service')], max_length=20)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.merchant')),
            ],
        ),
        migrations.AddIndex(
            model_name='tenantmembership',
            index=models.Index(fields=['user', 'is_active'], name='merchant_te_user_id_2fba0b_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantmembership',
            index=models.Index(fields=['tenant', 'is_active'], name='merchant_te_tenant__96eb63_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantmembership',
            unique_together={('user', 'tenant')},
        ),
        migrations.AddIndex(
            model_name='tenantinvitation',
            index=models.Index(fields=['token'], name='merchant_te_token_546b47_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantinvitation',
            index=models.Index(fields=['email', 'status'], name='merchant_te_email_3dd861_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantinvitation',
            unique_together={('email', 'tenant')},
        ),
    ]
