# Generated by Django 3.2 on 2025-05-16 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0002_initial'),
        ('offer', '0001_initial'),
        ('store_meta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rangeproductfileupload',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By'),
        ),
        migrations.AddField(
            model_name='rangeproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.product'),
        ),
        migrations.AddField(
            model_name='rangeproduct',
            name='range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.range'),
        ),
        migrations.AddField(
            model_name='range',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='classes', to='catalogue.ProductClass', verbose_name='Product Types'),
        ),
        migrations.AddField(
            model_name='range',
            name='excluded_products',
            field=models.ManyToManyField(blank=True, related_name='excluded_from_ranges', to='catalogue.Product'),
        ),
        migrations.AddField(
            model_name='range',
            name='included_categories',
            field=models.ManyToManyField(blank=True, related_name='includes', to='catalogue.Category', verbose_name='Included Categories'),
        ),
        migrations.AddField(
            model_name='range',
            name='included_products',
            field=models.ManyToManyField(blank=True, related_name='included_in_ranges', through='offer.RangeProduct', to='catalogue.Product'),
        ),
        migrations.AddField(
            model_name='range',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='store_meta.store', verbose_name='Store'),
        ),
        migrations.AddField(
            model_name='conditionaloffercombination',
            name='primary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_combinations', to='offer.conditionaloffer'),
        ),
        migrations.AddField(
            model_name='conditionaloffercombination',
            name='secondary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_combinations', to='offer.conditionaloffer'),
        ),
        migrations.AddField(
            model_name='conditionaloffer',
            name='benefit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_conditional_offers', to='offer.benefit'),
        ),
        migrations.AddField(
            model_name='conditionaloffer',
            name='combinations',
            field=models.ManyToManyField(help_text='Select other offers to combine with this one', through='offer.ConditionalOfferCombination', to='offer.ConditionalOffer', verbose_name='Combinations'),
        ),
        migrations.AddField(
            model_name='conditionaloffer',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_conditional_offers', to='offer.condition'),
        ),
        migrations.AddField(
            model_name='conditionaloffer',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='store_meta.store', verbose_name='Store'),
        ),
        migrations.AddField(
            model_name='condition',
            name='range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offer.range', verbose_name='Range'),
        ),
        migrations.AddField(
            model_name='condition',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='store_meta.store'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offer.range', verbose_name='Range'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='store_meta.store'),
        ),
        migrations.CreateModel(
            name='AbsoluteDiscountBenefit',
            fields=[
            ],
            options={
                'verbose_name': 'Absolute discount benefit',
                'verbose_name_plural': 'Absolute discount benefits',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('offer.benefit',),
        ),
        migrations.CreateModel(
            name='CountCondition',
            fields=[
            ],
            options={
                'verbose_name': 'Count condition',
                'verbose_name_plural': 'Count conditions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('offer.condition',),
        ),
        migrations.CreateModel(
            name='CoverageCondition',
            fields=[
            ],
            options={
                'verbose_name': 'Coverage Condition',
                'verbose_name_plural': 'Coverage Conditions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('offer.condition',),
        ),
        migrations.CreateModel(
            name='FixedPriceBenefit',
            fields=[
            ],
            options={
                'verbose_name': 'Fixed price benefit',
                'verbose_name_plural': 'Fixed price benefits',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('offer.benefit',),
        ),
        migrations.CreateModel(
            name='MultibuyDiscountBenefit',
            fields=[
            ],
            options={
                'verbose_name': 'Multibuy discount benefit',
                'verbose_name_plural': 'Multibuy discount benefits',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('offer.benefit',),
        ),
        migrations.CreateModel(
            name='PercentageDiscountBenefit',
            fields=[
            ],
            options={
                'verbose_name': 'Percentage discount benefit',
                'verbose_name_plural': 'Percentage discount benefits',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('offer.benefit',),
        ),
        migrations.CreateModel(
            name='ShippingBenefit',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('offer.benefit',),
        ),
        migrations.CreateModel(
            name='ValueCondition',
            fields=[
            ],
            options={
                'verbose_name': 'Value condition',
                'verbose_name_plural': 'Value conditions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('offer.condition',),
        ),
        migrations.AlterUniqueTogether(
            name='conditionaloffercombination',
            unique_together={('primary', 'secondary')},
        ),
        migrations.CreateModel(
            name='ShippingAbsoluteDiscountBenefit',
            fields=[
            ],
            options={
                'verbose_name': 'Shipping absolute discount benefit',
                'verbose_name_plural': 'Shipping absolute discount benefits',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('offer.shippingbenefit',),
        ),
        migrations.CreateModel(
            name='ShippingFixedPriceBenefit',
            fields=[
            ],
            options={
                'verbose_name': 'Fixed price shipping benefit',
                'verbose_name_plural': 'Fixed price shipping benefits',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('offer.shippingbenefit',),
        ),
        migrations.CreateModel(
            name='ShippingPercentageDiscountBenefit',
            fields=[
            ],
            options={
                'verbose_name': 'Shipping percentage discount benefit',
                'verbose_name_plural': 'Shipping percentage discount benefits',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('offer.shippingbenefit',),
        ),
    ]
